### ISSUE TITLE
Support for statsd sets

### ISSUE THREAD

**Issue by cutz** [zodb/perfmetrics#3]
Statsd supports a [Set](https://github.com/etsy/statsd/blob/master/docs/metric_types.md#sets) metric type for "... counting unique occurences of events between flushes ...". The existing statsd client implemented here doesn't provide a public method suitable for sending metrics of this type. Would you be willing to accept a PR implementing this functionality?

**Comment by jamadden** [comment]
Yes, I think it makes sense to take a PR for that. 

First, though, let me do some cleanups and modernizations in this repo to make sure we're in a good state.
